### ISSUE TITLE
Building issue : Could not find artifact dcm4chee-conf-cdi-producer

### ISSUE THREAD

**Issue by scupperscupper** [dcm4che/dcm4chee-conf#4]
In the pom.xml file under dcm4chee-conf/dcm4chee-conf-jboss-modules there's this dependency declaration that makes the build for the cdi producer fail.

```
<dependencies>
    <dependency>
      <groupId>org.dcm4che.dcm4chee-conf</groupId>
      <artifactId>dcm4chee-conf-cdi-producer</artifactId>
      <version>${project.version}</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
```

<html><b><i>
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5:single (default) on project dcm4chee-conf-jboss-modules: Failed to create assembly: Failed to resolve dependencies for project: org.dcm4che.dcm4chee-conf:dcm4chee-conf-jboss-modules:pom:1.1.0-SNAPSHOT: Could not find artifact org.dcm4che.dcm4chee-conf:dcm4chee-conf-cdi-producer:jar:1.1.0-SNAPSHOT
</i></b></html>

**Comment by hczedik** [comment]
The problem has been fixed.
Thanks for reporting!
